### ISSUE TITLE
Usability: consider always showing the "secret" field

### ISSUE THREAD

**Issue by itsadok** [chriszarate/supergenpass#51]
I just spent a few minutes trying to figure out why I was getting different results between my phone and my desktop, until I realized that I had an extension auto-filling the "Secret Password" field on the desktop.

(Ironically, it was the SuperGenPass Chrome Session extension, but it could have been anything).

Looking over the issues list, I see somebody was already bitten by this in #44, and I suspect that #35 was also about this problem.

I suggest you either always show the secret password field so that people would be able to see if it was auto-filled, or better yet, generate the field dynamically when hitting the "Options" button, so that there's no chance for it to be auto-filled.

**Comment by chriszarate** [comment]
A quick indicator that a secret password is already set is a visible identicon in the master password field before you start typing.

That said, I think this can be addressed by the proposed fix for #57.

**Comment by brianclements** [comment]
At least for my usage, the question is not whether it's set or not, but merely a preference to always have it open and accessible so that I don't have to click the gear icon constantly to reveal it. I guess my ideal would be to have only the password length and hash algorithm be hidden with the gear icon. This could encourage use of the secret field as well which I feel has many benefits.
