### ISSUE TITLE
Why is minimal password length be 4?

### ISSUE THREAD

**Issue by weakish** [chriszarate/supergenpass#84]
I guess a lot of sites refuse accept 4 character password.

Also, the minimal password length to satisfies 1) starts with lower case 2) contains at least one upper caes and one digital is 3.

So `4` is neither the minimal value in practical applications, nor the shortest possible value in algorithm.
Why dose SuperGenPass pick `4` as minimal value?

**Comment by chriszarate** [comment]
Generating a three-digit password with SGP requires a large amount of additional hashing to satisfy the complexity requirements. Four-digit passwords are generated with much less additional hashing. SGP was designed to work with as many websites as possible, so I chose 4 as the minimum since I had no way of auditing the requirements of all websites. I strongly discourage the use of passwords less than the default of 10 characters. Ideally, set your default to 20 or higher.
